Resources:
  CrmWithXeroStatusMapping:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: TblCrmWithXeroStatusMapping
      AttributeDefinitions:
        - AttributeName: UserId
          AttributeType: S        
        - AttributeName: CombinedSortKey
          AttributeType: S

      KeySchema:
        - AttributeName: UserId
          KeyType: HASH
        - AttributeName: CombinedSortKey
          KeyType: RANGE       
      BillingMode: PAY_PER_REQUEST
