Resources:
  CrmWithXeroTaxMapping:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: TblCrmWithXeroTaxMapping
      AttributeDefinitions:
        - AttributeName: UserId
          AttributeType: S        
        - AttributeName: CombinedSortKey
          AttributeType: S

      KeySchema:
        - AttributeName: UserId
          KeyType: HASH
        - AttributeName: CombinedSortKey
          KeyType: RANGE       
      BillingMode: PAY_PER_REQUEST
