Resources:
  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
        TableName: TblUsers
        AttributeDefinitions:
            - AttributeName: UserId
              AttributeType: S
        KeySchema:
            - AttributeName: UserId
              KeyType: HASH
        BillingMode: PAY_PER_REQUEST